finalcore/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name='finalcore'

urlpatterns = [
    path('wordcases', views.WorldCasesView.as_view(),name = 'word_case'),
    path('us-state', views.USStateView.as_view(),name = 'us_state'),
    path('us-county', views.USCountyView.as_view(),name = 'us_county'),
    path('us-projection', views.USProjection.as_view(),name = 'us_projection'),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('finalcore/', include('finalcore.urls'))
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    # path('home', views.HomeView.as_view() ),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations

class HomeView(View):
    def get(self, request) :
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed' : settings.INSTALLED_APPS,
            'islocal' : islocal
        }
        return render(request, 'home/index.html', context)
from django.shortcuts import render

# Create your views here.

home/templates/base_bootstrap.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<title>507 Final Project {% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
{% block hdr %}
{% endblock %}
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-info">
      <a class="navbar-brand" href="{% url 'home:index' %}">Xin Hu 507 Final Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <!-- <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
              </li> -->
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">
                      Visualization
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'finalcore:word_case' %}">World Cases</a>
                      <a class="dropdown-item" href="{% url 'finalcore:us_state' %}">US State Cases</a>
                      <a class="dropdown-item" href="{% url 'finalcore:us_county' %}">US County Cases</a>
                      <a class="dropdown-item" href="{% url 'finalcore:us_projection' %}">US Projection</a>
                  </div>
              </li>
          </ul>
      </div>
    </nav>
  </header>

  <div class="container">
  {% block content %}

  {% endblock %}
  </div>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>